#!/bin/bash

apt update
apt -y install git

## Not working
#git config --global url."https://github.com/".insteadOf git@github.com:
#git config --global url."https://".insteadOf git://

ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
